config/routes.rb
Rails.application.routes.draw do

  resources :evaluation_scores
  resources :selected_evaluation_items
  resources :evaluation_items
  resources :companies

  resources :interests
  post 'interests/add_company',to:'interests#add_company'
  
  resources :interest_memos
  get 'interest_memo/new.:interest_id',to:'interest_memo#create'

  resources :users
  resources :sessions, only: [:new,:create,:destroy]
  get 'signup',to:'users#new'
  get 'login',to:'sessions#new'
  post 'login',to:'sessions#create'
  delete 'logout',to:'sessions#destroy'

  root to: 'static_pages#home'
  get 'admincompanies',to:'admincompanies#index'
  

end

app/models/interest.rb
class Interest < ActiveRecord::Base
    validates :score,  numericality: {
            only_integer: true,
            greater_than_or_equal_to: 0,
            less_than_or_equal_to: 10
          }
    belongs_to :user
    belongs_to :company
    has_many :interest_memos
    has_many :evaluation_scores
    has_many :selected_evaluation_items, through: :evaluation_scores
    accepts_nested_attributes_for :evaluation_scores

end

app/controllers/interests_controller.rb
class InterestsController < ApplicationController
  before_action :set_interest, only: [:show, :edit, :update, :destroy]

  # GET /interests
  # GET /interests.json
  def index
    @interests = Interest.all
  end

  # GET /interests/1
  # GET /interests/1.json
  def show
    @interest_memos = @interest.interest_memos
    @evaluation_scores = @interest.evaluation_scores.includes(:selected_evaluation_item)
    graph
    
  end

  # GET /interests/new
  def new
    @interest = Interest.new
  end

  # GET /interests/1/edit
  def edit
    @array_evaluation_titles = EvaluationItem.all.pluck(:title)
  end

  # POST /interests
  # POST /interests.json
  def create
    @interest = Interest.new(interest_params)

    respond_to do |format|
      if @interest.save
        format.html { redirect_to @interest, notice: '選考状況概要を更新しました。' }
        format.json { render :show, status: :created, location: @interest }
      else
        format.html { render :new }
        format.json { render json: @interest.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /interests/addCompany
  def add_company
    @interest = Interest.new()
    @interest.company_id = params['company_id']
    @interest.user_id = current_user.id
    @interest.score = 0
    @interest.status = "情報収集中"

    respond_to do |format|
      if @interest.save
        format.html { redirect_to current_user, notice: 'Interest was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end


  # PATCH/PUT /interests/1
  # PATCH/PUT /interests/1.json
  def update
    respond_to do |format|
      if @interest.update(interest_params)
        format.html { redirect_to @interest, notice: 'Interest was successfully updated.' }
        format.json { render :show, status: :ok, location: @interest }
      else
        format.html { render :edit }
        format.json { render json: @interest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interests/1
  # DELETE /interests/1.json
  def destroy
    @interest.destroy
    respond_to do |format|
      format.html { redirect_to interests_url, notice: 'Interest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def graph
      array_evaluation_titles = EvaluationItem.all.pluck(:title)
      array_evaluation_scores = @evaluation_scores.pluck(:score)
      
      @graph = LazyHighCharts::HighChart.new('graph') do |f|
        f.chart(polar: true,type:'line') #グラフの種類
        f.pane(size:'80%')                  #グラフサイズの比
        f.title(text: "総合得点： #{@interest.score} / 10" )         #タイトル
        f.xAxis(categories: array_evaluation_titles,tickmarkPlacement:'on')
        #categories:各項目の名前,tickmarkPlacement:'on'だとメモリ表示がカテゴリーの表示に沿う
        f.yAxis(gridLineInterpolation: 'polygon',lineWidth:0,min:0,max:5) #各項目の最大値やら
        f.series(name:'あなたの評価',data: array_evaluation_scores,pointPlacement:'on')
       #各データ
        f.legend(align: 'right',
  	        verticalAlign: 'top',
  	        y: 70,
  	        layout: 'vertical')
	     
      end
  end    


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_interest
      @interest = Interest.find(params[:id])
      check_mine
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def interest_params
      params.require(:interest).permit(:user_id, :company_id,:score, :status, :date, evaluation_scores_attributes: [:score,:id])
    end
    
    def check_mine
      redirect_to current_user unless mine?(@interest.user_id)
    end

end

app/helpers/interests_helper.rb
module InterestsHelper
end

app/views/interests/_form.html.erb
<%= form_for(@interest) do |f| %>
  <% if @interest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@interest.errors.count, "error") %> prohibited this interest from being saved:</h2>

      <ul>
      <% @interest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<!--
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id , {class: "form-control"}%>
  </div>
  <div class="field">
    <%= f.label :company_id %><br>
    <%= f.number_field :company_id , {class: "form-control"}%>
  </div>
-->
  <div class="field">
    <%= f.label :score %><br>
    <%= f.number_field :score , {class: "form-control"}%>
  </div>


  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status , {class: "form-control"}%>
  </div>
  
  <%= f.label :date %>
  <div class='input-group date datepicker field'>
   <%= f.text_field :date, class: 'form-control' %>
   <span class="input-group-addon">
       <span class="glyphicon glyphicon-calendar"></span>
   </span>
  </div>  
  
  
  <% #各項目の評価入力箇所 %>
  <%= f.fields_for :evaluation_scores do |evaluation_score| %>
    <div class="field">
      <%= @array_evaluation_titles[evaluation_score.object.selected_evaluation_item_id.to_i-1] %>
      <%= evaluation_score.number_field :score %>
    </div>

  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>

  
  
  <div class="actions">
    <%= f.submit "更新する"%>
  </div>
<% end %>

app/views/interests/_interest.html.erb
<tr id="company-<%= interest.company.id %>">
  <td><img border="0" height="60px" src="<%= interest.company.logoURL %>" alt="logo"></td>

  <td><p class="text-center" valign="middle">
     <%= link_to interest.company.name,  interest_path(interest.id) %>
  </p></td>

  <td><p class="text-center" valign="middle">
     <%= link_to interest.score||=0,  edit_interest_path(interest.id) %>
  </p></td>


  <td><p class="text-center" valign="middle">
    <% label_tag = make_label_class(interest.status)%>
    <%= content_tag(:span, interest.status, class: ["label",label_tag,"status-label"])%>

  </p></td>
  <td><p class="text-center" valign="middle"><%= interest.date %></p></td>
</tr>

app/views/interests/edit.html.erb
<h1>企業評価と状況の更新</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/interests/index.html.erb
 

<h1>Listing Interests</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Company</th>
      <th>Status</th>
      <th>Datetime</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @interests.each do |interest| %>
      <tr>
        <td><%= interest.user_id %></td>
        <td><%= interest.company_id %></td>
        <td><%= interest.status %></td>
        <td><%= interest.date %></td>
        <td><%= link_to 'Show', interest %></td>
        <td><%= link_to 'Edit', edit_interest_path(interest) %></td>
        <td><%= link_to 'Destroy', interest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Interest', new_interest_path %>

app/views/interests/new.html.erb
<h1>New Interest</h1>

<%= render 'form' %>

<%= link_to 'Back', interests_path %>

app/views/interests/show.html.erb
<hr>
  <div>
    <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
    <%= link_to '関心企業一覧', user_path(@interest.user_id) %>
     /   <%= @interest.company.name %>
  </div>
<hr>



<div class="page-header">
  <h4><span class="glyphicon glyphicon-inbox"></span> 選考状況概要 
  <small>この会社の現在の状況は？</small></h4>
</div>

<ul class="list-group">
  <li class="list-group-item list-group-item-warning">
      会社名
  </li>
  <li class="list-group-item">
    <p>
      <%= @interest.company.name %>
    </p>
  </li>
  <li class="list-group-item list-group-item-warning">
      自己総合評価
  </li>
  <li class="list-group-item">
    <p>
      <%= @interest.score %>
    </p>
  </li>
  <li class="list-group-item list-group-item-warning">
      選考状況
  </li>
  <li class="list-group-item">
    <p>
      <%= @interest.status %>
    </p>
  </li>
  <li class="list-group-item list-group-item-warning">
      次の日付
  </li>
  <li class="list-group-item">
    <p>
      <%= @interest.date %>
    </p>
  </li>
</ul>

<%= link_to edit_interest_path(@interest) do %>
    <span class="glyphicon glyphicon-pencil"></span>
    この企業の選考概要を更新する
<% end %>


<hr>


<div class="page-header">
  <h4><span class="glyphicon glyphicon-book"></span> 企業評価
  <small>この会社に関しての自分の評価結果</small></h4>
</div>

<%= high_chart("radar", @graph) %>



<hr>


<div class="page-header">
  <h4><span class="glyphicon glyphicon-book"></span> 今までの記録
  <small>この会社に関係したセミナーや面接をメモしよう！</small></h4>
</div>


<ul class="list-group">
  <% @interest_memos.each do |f| %>
  <li class="list-group-item list-group-item-warning">
      <%= link_to edit_interest_memo_path(f) do %>
          <span class="glyphicon glyphicon-calendar"></span>
          <%= f.date %>
      <% end %>
  </li>
  <li class="list-group-item">
    <p>
      <p class="list-group-item-text"><%= simple_format(f.memo) %></p>
    </p>
  </li>
  <% end %>
</ul>

<%= link_to new_interest_memo_path(:interest_id => @interest.id) do %>
    <span class="glyphicon glyphicon-pencil"></span>
    新しい記録を残す
<% end %>

<hr>

<%= link_to 'ホームに戻る', user_path(@interest.user_id) %>