config/routes.rb
Rails.application.routes.draw do

  resources :evaluation_scores
  resources :selected_evaluation_items
  resources :evaluation_items
  resources :companies

  resources :interests
  post 'interests/add_company',to:'interests#add_company'
  
  resources :interest_memos
  get 'interest_memo/new.:interest_id',to:'interest_memo#create'

  resources :users
  resources :sessions, only: [:new,:create,:destroy]
  get 'signup',to:'users#new'
  get 'login',to:'sessions#new'
  post 'login',to:'sessions#create'
  delete 'logout',to:'sessions#destroy'

  root to: 'static_pages#home'
  get 'admincompanies',to:'admincompanies#index'
  

end

app/models/evaluation_item.rb
class EvaluationItem < ActiveRecord::Base
 has_many :selected_evaluation_items
end

app/controllers/evaluation_items_controller.rb
class EvaluationItemsController < ApplicationController
  before_action :set_evaluation_item, only: [:show, :edit, :update, :destroy]

  # GET /evaluation_items
  # GET /evaluation_items.json
  def index
    @evaluation_items = EvaluationItem.all
  end

  # GET /evaluation_items/1
  # GET /evaluation_items/1.json
  def show
  end

  # GET /evaluation_items/new
  def new
    @evaluation_item = EvaluationItem.new
  end

  # GET /evaluation_items/1/edit
  def edit
  end

  # POST /evaluation_items
  # POST /evaluation_items.json
  def create
    @evaluation_item = EvaluationItem.new(evaluation_item_params)

    respond_to do |format|
      if @evaluation_item.save
        format.html { redirect_to @evaluation_item, notice: 'Evaluation item was successfully created.' }
        format.json { render :show, status: :created, location: @evaluation_item }
      else
        format.html { render :new }
        format.json { render json: @evaluation_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /evaluation_items/1
  # PATCH/PUT /evaluation_items/1.json
  def update
    respond_to do |format|
      if @evaluation_item.update(evaluation_item_params)
        format.html { redirect_to @evaluation_item, notice: 'Evaluation item was successfully updated.' }
        format.json { render :show, status: :ok, location: @evaluation_item }
      else
        format.html { render :edit }
        format.json { render json: @evaluation_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /evaluation_items/1
  # DELETE /evaluation_items/1.json
  def destroy
    @evaluation_item.destroy
    respond_to do |format|
      format.html { redirect_to evaluation_items_url, notice: 'Evaluation item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_evaluation_item
      @evaluation_item = EvaluationItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def evaluation_item_params
      params.require(:evaluation_item).permit(:title)
    end
end

app/helpers/evaluation_items_helper.rb
module EvaluationItemsHelper
end

app/views/evaluation_items/_form.html.erb
<%= form_for(@evaluation_item) do |f| %>
  <% if @evaluation_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@evaluation_item.errors.count, "error") %> prohibited this evaluation_item from being saved:</h2>

      <ul>
      <% @evaluation_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/evaluation_items/edit.html.erb
<h1>Editing Evaluation Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @evaluation_item %> |
<%= link_to 'Back', evaluation_items_path %>

app/views/evaluation_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Evaluation Items</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @evaluation_items.each do |evaluation_item| %>
      <tr>
        <td><%= evaluation_item.title %></td>
        <td><%= link_to 'Show', evaluation_item %></td>
        <td><%= link_to 'Edit', edit_evaluation_item_path(evaluation_item) %></td>
        <td><%= link_to 'Destroy', evaluation_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Evaluation item', new_evaluation_item_path %>

app/views/evaluation_items/new.html.erb
<h1>New Evaluation Item</h1>

<%= render 'form' %>

<%= link_to 'Back', evaluation_items_path %>

app/views/evaluation_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @evaluation_item.title %>
</p>

<%= link_to 'Edit', edit_evaluation_item_path(@evaluation_item) %> |
<%= link_to 'Back', evaluation_items_path %>