config/routes.rb
Rails.application.routes.draw do

  resources :evaluation_scores
  resources :selected_evaluation_items
  resources :evaluation_items
  resources :companies

  resources :interests
  post 'interests/add_company',to:'interests#add_company'
  
  resources :interest_memos
  get 'interest_memo/new.:interest_id',to:'interest_memo#create'

  resources :users
  resources :sessions, only: [:new,:create,:destroy]
  get 'signup',to:'users#new'
  get 'login',to:'sessions#new'
  post 'login',to:'sessions#create'
  delete 'logout',to:'sessions#destroy'

  root to: 'static_pages#home'
  get 'admincompanies',to:'admincompanies#index'
  

end

app/models/interest_memo.rb
class InterestMemo < ActiveRecord::Base
    belongs_to :interest
end

app/controllers/interest_memos_controller.rb
class InterestMemosController < ApplicationController
  before_action :set_interest_memo, only: [:show, :edit, :update, :destroy]

  # GET /interest_memos
  # GET /interest_memos.json
  def index
    @interest_memos = InterestMemo.all
  end

  # GET /interest_memos/1
  # GET /interest_memos/1.json
  def show
  end

  # GET /interest_memos/new
  def new
    @interest_memo = InterestMemo.new({'interest_id':params['interest_id']})
  end

  # GET /interest_memos/1/edit
  def edit
  end

  # POST /interest_memos
  # POST /interest_memos.json
  def create
    @interest_memo = InterestMemo.new(interest_memo_params)

    respond_to do |format|
      if @interest_memo.save
        format.html { redirect_to interest_path(@interest_memo.interest_id), notice: '新しいメモを作成しました' }
        format.json { render :show, status: :created, location: @interest_memo }
      else
        format.html { render :new }
        format.json { render json: @interest_memo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /interest_memos/1
  # PATCH/PUT /interest_memos/1.json
  def update
    respond_to do |format|
      if @interest_memo.update(interest_memo_params)
        format.html { redirect_to @interest_memo.interest, notice: '選考状況概要を更新しました。' }
        format.json { render :show, status: :ok, location: @interest_memo }
      else
        format.html { render :edit }
        format.json { render json: @interest_memo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interest_memos/1
  # DELETE /interest_memos/1.json
  def destroy
    @interest_memo.destroy
    respond_to do |format|
      format.html { redirect_to interest_memos_url, notice: 'Interest memo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_interest_memo
      @interest_memo = InterestMemo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def interest_memo_params
      params.require(:interest_memo).permit(:interest_id, :date, :memo)
    end
end

app/helpers/interest_memos_helper.rb
module InterestMemosHelper
end

app/views/interest_memos/_form.html.erb
<%= form_for(@interest_memo) do |f| %>
  <% if @interest_memo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@interest_memo.errors.count, "error") %> prohibited this interest_memo from being saved:</h2>

      <ul>
      <% @interest_memo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div>
    <%= f.hidden_field :interest_id, :value => @interest_memo.interest_id %>
  </div>

  <%= f.label :date %>
  <div class='input-group date datepicker'>
   <%= f.text_field :date, class: 'form-control' %>
   <span class="input-group-addon">
       <span class="glyphicon glyphicon-calendar"></span>
   </span>
  </div>  

  <div class="field">
    <%= f.label :memo %><br>
    <%= f.text_area :memo, :size=>"60x15"%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/interest_memos/edit.html.erb
<h1>Editing Interest Memo</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/interest_memos/index.html.erb
 

<h1>Listing Interest Memos</h1>

<table>
  <thead>
    <tr>
      <th>Interest</th>
      <th>Date</th>
      <th>Memo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @interest_memos.each do |interest_memo| %>
      <tr>
        <td><%= interest_memo.interest_id %></td>
        <td><%= interest_memo.date %></td>
        <td><%= interest_memo.memo %></td>
        <td><%= link_to 'Show', interest_memo %></td>
        <td><%= link_to 'Edit', edit_interest_memo_path(interest_memo) %></td>
        <td><%= link_to 'Destroy', interest_memo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Interest memo', new_interest_memo_path %>

app/views/interest_memos/new.html.erb
<h1>New Interest Memo</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/interest_memos/show.html.erb
 

<p>
  <strong>Interest:</strong>
  <%= @interest_memo.interest_id %>
</p>

<p>
  <strong>Date:</strong>
  <%= @interest_memo.date %>
</p>

<p>
  <strong>Memo:</strong>
  <%= @interest_memo.memo %>
</p>

<%= link_to 'Edit', edit_interest_memo_path(@interest_memo) %> |
<%= link_to 'Back', interest_memos_path %>